CREATE TABLE [IM].[IM_COMPANY] (
    [ID]           VARCHAR (36)   NOT NULL,
    [NAME]         NVARCHAR (100) NOT NULL,
    [ADDRESS]      VARCHAR (100)  NULL,
    [ADDRESS1]     VARCHAR (100)  NULL,
    [ADDRESS2]     VARCHAR (100)  NULL,
    [PHONENUMBER]  VARCHAR (20)   NULL,
    [FAXNUMBER]    VARCHAR (20)   NULL,
    [DOMAIN]       VARCHAR (350)  NULL,
    [TRADELICENSE] VARCHAR (100)  NULL,
    [CREATEDBY]    NVARCHAR (200) NOT NULL,
    [CREATEDDATE]  DATETIME       NOT NULL,
    [UPDATEDBY]    NVARCHAR (200) NULL,
    [UPDATEDDATE]  DATETIME       NULL,
    [ACTIVE]       BIT            NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [Unique_Constaint_IM_COMPANY_NAME] UNIQUE NONCLUSTERED ([NAME] ASC)
);

