CREATE TABLE [IM].[IM_GROUPS_OU] (
    [ID]          VARCHAR (36)   NOT NULL,
    [GROUP_ID]    VARCHAR (36)   NOT NULL,
    [OU_ID]       VARCHAR (36)   NOT NULL,
    [CREATEDBY]   NVARCHAR (200) NOT NULL,
    [CREATEDDATE] DATETIME       NOT NULL,
    [UPDATEDBY]   NVARCHAR (200) NULL,
    [UPDATEDDATE] DATETIME       NULL,
    [ACTIVE] BIT DEFAULT ((1)) NOT NULL, 
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([GROUP_ID]) REFERENCES [IM].[IM_GROUPS] ([ID]),
    FOREIGN KEY ([OU_ID]) REFERENCES [IM].[IM_OU] ([ID]),
    CONSTRAINT [Unique_Constaint_IM_USER_OU] UNIQUE NONCLUSTERED ([GROUP_ID] ASC, [OU_ID] ASC)
);

