CREATE TABLE [IM].[IM_GROUPS] (
    [ID]          VARCHAR (36)   NOT NULL,
    [NAME]        VARCHAR (255)  NOT NULL,
    [REMARKS]     NVARCHAR (255) NULL,
    [ACTIVE]      BIT            DEFAULT ((1)) NOT NULL,
    [CREATEDBY]   NVARCHAR (200) NOT NULL,
    [CREATEDDATE] DATETIME       NOT NULL,
    [UPDATEDBY]   NVARCHAR (200) NULL,
    [UPDATEDDATE] DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [Unique_Constaint_IM_GROUPS] UNIQUE NONCLUSTERED ([NAME] ASC)
);

