CREATE TABLE [IM].[IM_TEMPLATE_SETTING]
(
	[ID] NVARCHAR (36) NOT NULL PRIMARY KEY,
	[NAME]   NVARCHAR (320) NOT NULL,
    [KEY]   NVARCHAR (320) NOT NULL,
    [VALUE]   VARCHAR (MAX) NOT NULL,
	[ACTIVE]   bit NOT NULL default(0),
	[DESCRIPTION]   NVARCHAR (MAX) NOT NULL,
    [CREATEDBY]   NVARCHAR (200) NOT NULL,
    [CREATEDDATE] DATETIME       NOT NULL,
    [UPDATEDBY]   NVARCHAR (200) NULL,
    [UPDATEDDATE] DATETIME       NULL 
)
