CREATE TABLE [IM].[IM_USER_METADATA] (
    [ID]          VARCHAR (36)   NOT NULL,
    [USER_NAME]   NVARCHAR (320) NOT NULL,
    [METADATA]    NVARCHAR (MAX) NOT NULL,
    [METATYPE]    VARCHAR (36)   NULL,
    [CREATEDBY]   NVARCHAR (200) NOT NULL,
    [CREATEDDATE] DATETIME       NOT NULL,
    [UPDATEDBY]   NVARCHAR (200) NULL,
    [UPDATEDDATE] DATETIME       NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)    
);

