name: Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore FleetMgmt.Identity/FleetMgmt.Identity.sln
    - name: Build
      run: dotnet build FleetMgmt.Identity/API/FleetMgmt.Identity.API/FleetMgmt.Identity.API.csproj  --configuration Release --no-restore | dotnet build FleetMgmt.Identity/Api\ Gateway/FleetMgmt.Identity.Gateway/FleetMgmt.Identity.Gateway.csproj --configuration Release --no-restore

    - name: Publish API
      run: |
        dotnet publish FleetMgmt.Identity/API/FleetMgmt.Identity.API/FleetMgmt.Identity.API.csproj -c Release -o identity-api
        
    - name: Publish Gateway
      run: |
        dotnet publish FleetMgmt.Identity/Api\ Gateway/FleetMgmt.Identity.Gateway/FleetMgmt.Identity.Gateway.csproj -c Release -o identity-gateway
        
     #substitute production appsettings entries to appsettings json file
    - name: Gateway App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: './identity-gateway/appsettings.json'
      env:
        ReRoutes.0.DownstreamScheme: "https"
        ReRoutes.0.DownstreamHostAndPorts.0.Host: "fleetmgmt-identity.azurewebsites.net"
        ReRoutes.0.DownstreamHostAndPorts.0.Port: "80"
        ReRoutes.1.DownstreamScheme: "https"
        ReRoutes.1.DownstreamHostAndPorts.0.Host: "fleetmgmt-identity.azurewebsites.net"
        ReRoutes.1.DownstreamHostAndPorts.0.Port: "80"
        ReRoutes.2.DownstreamScheme: "https"
        ReRoutes.2.DownstreamHostAndPorts.0.Host: "fleetmgmt-identity.azurewebsites.net"
        ReRoutes.2.DownstreamHostAndPorts.0.Port: "80"

    - uses: azure/webapps-deploy@v1
      with:
        app-name: fleetmgmt-identity-api
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: './identity-api'
        
    - uses: azure/webapps-deploy@v1
      with:
        app-name: fleetmgmt-identity-gateway
        publish-profile: ${{ secrets.azureGatewayPublishProfile }}
        package: './identity-gateway'
